title:              Siddharth Singh
email:              Siddharth.Singh89@live.com
description:        Machine Learning Blog
author:             Siddharth Singh
baseurl:            "/"
url:                "https://siddharth-singh.com"

# Social Profiles
twitter_username:   siddharthsingh89
github_username:    siddharthsingh89
linkedin_username:  siddharthsingh89

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
